package com.dental.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BuildingOneDesign extends CssLayout {
	protected Label billing_header_label;
	protected CssLayout dashboard_item5;
	protected Label dashboard_item_header;
	protected Label statistics_label;
	protected Button bUitbereding1;
	protected Label statistics_label1;
	protected Button bGebouw1;
	protected Label statistics_label2;
	protected Button bUitbereiding2;
	protected Label statistics_label3;
	protected Button bUitbereiding3;
	protected Label statistics_label31;
	protected Button bAlleVerlichting;
	protected Label statistics_label32;
	protected Button bGas;
	protected CssLayout dashboard_item26;
	protected Label dashboard_item_header2;
	protected Label statistics_label11;
	protected Button bZoneStaal1a;
	protected Label statistics_label13;
	protected Button bZoneStaal1b;
	protected Label statistics_label14;
	protected Button bZoneMetaal1;
	protected Label statistics_label15;
	protected Button bZoneMetaal2;
	protected Label statistics_label110;
	protected Button bZoneGieten;
	protected Label statistics_label111;
	protected Button bZoneKronen;
	protected Label statistics_label112;
	protected Button bZoneGarage;
	protected CssLayout dashboard_item27;
	protected Label dashboard_item_header3;
	protected Label statistics_label113;
	protected Button bZoneLandscape;
	protected Label statistics_label114;
	protected Button bZonePorcelein;
	protected Label statistics_label115;
	protected Button bZoneZirkonium;
	protected Label statistics_label116;
	protected Button bZoneSpray;
	protected Label statistics_label117;
	protected Button bZoneMeten;
	protected Label statistics_label118;
	protected Button bZoneBurelen;
	protected Label statistics_label119;
	protected Button bZoneInkom;

	public BuildingOneDesign() {
		Design.read(this);
	}
}
