package com.dental.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BuildingDentalDesign extends GridLayout {
	protected Button bTrap;
	protected Button bBadkamerLed;
	protected Button bBadkamer;
	protected Button bFitness;
	protected Button bSlaapkamer;
	protected Button bNachthall;
	protected Button bLogeerkamer;
	protected Button bInkom1;
	protected Button bVestiaire;
	protected Button bLeefruimte1;
	protected Button bLeefruimte2;
	protected Button bLeefruimte3;
	protected Button bLeefruimteTafel;
	protected Button bKeukenKookblok;
	protected Button bKeuken;
	protected Button bBerging;
	protected Button bGarageProfiel;
	protected Button bGarageSpy;
	protected Button bTuinberging;
	protected Button bWijnkelder;
	protected Button bVoortuin;
	protected Button bVoortuinParking;
	protected Button bAchtertuinWand;
	protected Button bAchtertuinBoom;

	public BuildingDentalDesign() {
		Design.read(this);
	}
}
